"""create urls table

Revision ID: ec56027022db
Revises: 
Create Date: 2023-09-02 19:15:31.376251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec56027022db'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'urls',
        sa.Column('short_url', sa.String(), nullable=False),
        sa.Column('source_url', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('short_url', name=op.f('pk__urls')),
    )
    op.create_index(op.f('ix__urls__source_url'), 'urls', ['source_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__urls__source_url'), table_name='urls')
    op.drop_table('urls')
    # ### end Alembic commands ###
